document.writeln("<table width=\'98%\' align=\'left\' cellpadding=\'0\' cellspacing=\'0\' border=\'0\' bgcolor=\'#fff\' style=\'margin-top:300px; margin-left:10px;\' id=\'list\' class=\'list\'>");
document.writeln("<tr>");
document.writeln("    <td width=\'20\'>1</td>");
document.writeln("	<td class=\'bi\'><a href=\'http://dakawm.net:10802/\' target=\'_blank\'><strong>【大咖网盟】</strong>大咖网盟是一家没有中间商赚差价的直营广告联盟，数据真实不扣量。</a></td>");
document.writeln("</tr>");
document.writeln("</table>");
document.writeln("<table width=\'98%\' align=\'left\' cellpadding=\'0\' cellspacing=\'0\' border=\'0\' bgcolor=\'#fff\' style=\'margin-top:0px; margin-left:10px;\' id=\'list\' class=\'list\'>");
document.writeln("<tr>");
document.writeln("    <td width=\'20\'>2</td>");
document.writeln("    <td class=\'bi\'><a href=\'admin_reslib.php?ac=list&amp;rid=1&amp;url=http://cj.1156zy.com/inc/seacmsapi.php\'><strong>【33UU资源-综合】</strong></a>老牌资源分享网站 <a href=\'http://www.209zy.net/help/#SeaCms\' target=\'_blank\'>[采集帮助]</a></td>");
document.writeln("    <td><a href=\'admin_reslib.php?ac=day&amp;rid=1&amp;url=http://cj.1156zy.com/inc/seacmsapi.php\'>采集当天</a></td>");
document.writeln("    <td><a href=\'admin_reslib.php?ac=week&amp;rid=1&amp;url=http://cj.1156zy.com/inc/seacmsapi.php\'>采集本周</a></td>");
document.writeln("    <td><a href=\'admin_reslib.php?ac=all&amp;rid=1&amp;url=http://cj.1156zy.com/inc/seacmsapi.php\'>采集所有</a></td>");
document.writeln("    <td><a href=\'admin_reslib.php?ac=list&amp;rid=1&amp;url=http://cj.1156zy.com/inc/seacmsapi.php\'>分类绑定</a></td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("<tr>");
document.writeln("    <td width=\'20\'>3</td>");
document.writeln("    <td class=\'bi\'><a href=\'admin_reslib.php?ac=list&amp;rid=1&amp;url=http://cj.1156zy.com/inc/sea33uu.php\'><strong>【33UU资源-云播】</strong></a>老牌资源分享网站 <a href=\'http://www.209zy.net/help/#SeaCms\' target=\'_blank\'>[采集帮助]</a></td>");
document.writeln("    <td><a href=\'admin_reslib.php?ac=day&amp;rid=1&amp;url=http://cj.1156zy.com/inc/sea33uu.php\'>采集当天</a></td>");
document.writeln("    <td><a href=\'admin_reslib.php?ac=week&amp;rid=1&amp;url=http://cj.1156zy.com/inc/sea33uu.php\'>采集本周</a></td>");
document.writeln("    <td><a href=\'admin_reslib.php?ac=all&amp;rid=1&amp;url=http://cj.1156zy.com/inc/sea33uu.php\'>采集所有</a></td>");
document.writeln("    <td><a href=\'admin_reslib.php?ac=list&amp;rid=1&amp;url=http://cj.1156zy.com/inc/sea33uu.php\'>分类绑定</a></td>");
document.writeln("</tr>");
document.writeln("");
document.writeln("<tr>");
document.writeln("    <td width=\'20\'>4</td>");
document.writeln("    <td class=\'bi\'><a href=\'admin_reslib.php?ac=list&amp;rid=1&amp;url=http://cj.1156zy.com/inc/sea33uuck.php\'><strong>【33UU资源-m3u8】</strong></a>老牌资源分享网站 <a href=\'http://www.209zy.net/help/#SeaCms\' target=\'_blank\'>[采集帮助]</a></td>");
document.writeln("    <td><a href=\'admin_reslib.php?ac=day&amp;rid=1&amp;url=http://cj.1156zy.com/inc/sea33uuck.php\'>采集当天</a></td>");
document.writeln("    <td><a href=\'admin_reslib.php?ac=week&amp;rid=1&amp;url=http://cj.1156zy.com/inc/sea33uuck.php\'>采集本周</a></td>");
document.writeln("    <td><a href=\'admin_reslib.php?ac=all&amp;rid=1&amp;url=http://cj.1156zy.com/inc/sea33uuck.php\'>采集所有</a></td>");
document.writeln("    <td><a href=\'admin_reslib.php?ac=list&amp;rid=1&amp;url=http://cj.1156zy.com/inc/sea33uuck.php\'>分类绑定</a></td>");
document.writeln("</tr>");
document.writeln("</table>");
